//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cobaDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_Detail
    {
        public int Id { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual TB_M_Item TB_M_Item { get; set; }
        public virtual TB_M_Sell TB_M_Sell { get; set; }
    }
}
