// <auto-generated />
namespace cobaArray.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeAttributeItemsAndSupplierToPublic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeAttributeItemsAndSupplierToPublic));
        
        string IMigrationMetadata.Id
        {
            get { return "201903280728373_changeAttributeItemsAndSupplierToPublic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
